SELECT 
    d.DEPARTMENT_NAME AS 'NAMA DEPARTMENT',
    e.SALARY AS 'GAJI PALING BESAR',
    e.EMPLOYEE_ID AS 'ID PEGAWAI',
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS 'NAMA PEGAWAI'
FROM employees e
JOIN departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE (d.DEPARTMENT_ID, e.SALARY) IN (
	SELECT
    	DEPARTMENT_ID,
    	MAX(SALARY)
    FROM employees
    GROUP BY DEPARTMENT_ID
);