SELECT
	CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS 'NAMA',
    CONCAT(m.FIRST_NAME, ' ', m.LAST_NAME) AS 'NAMA MANAGERNYA'

FROM employees e
JOIN departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN employees m ON e.MANAGER_ID = m.EMPLOYEE_ID

WHERE d.DEPARTMENT_NAME = 'IT';