SELECT
	d.DEPARTMENT_NAME AS 'Nama Department',
    COUNT(e.DEPARTMENT_ID) AS 'Jumlah'
FROM  departments d
LEFT JOIN employees e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME, e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_NAME ASC;