SELECT
	d.DEPARTMENT_ID,
	d.DEPARTMENT_NAME,
	AVG(e.SALARY) AS 'GAJI',
    COUNT(e.EMPLOYEE_ID) AS 'TOTAL PEGAWAI LEBIH DARI 10'
FROM employees e
JOIN departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID
HAVING `TOTAL PEGAWAI LEBIH DARI 10` > 10;